/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ComptrollerV1Storage } from "./ComptrollerV1Storage";
export type { ComptrollerV2Storage } from "./ComptrollerV2Storage";
export type { ComptrollerV3Storage } from "./ComptrollerV3Storage";
export type { ComptrollerV4Storage } from "./ComptrollerV4Storage";
export type { ComptrollerV5Storage } from "./ComptrollerV5Storage";
export type { ComptrollerV6Storage } from "./ComptrollerV6Storage";
export type { ComptrollerV7Storage } from "./ComptrollerV7Storage";
export type { UnitrollerAdminStorage } from "./UnitrollerAdminStorage";
