/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as governorAlphaSol from "./GovernorAlpha.sol";
export * as governorBravoDelegateG1Sol from "./GovernorBravoDelegateG1.sol";
export * as governorBravoInterfacesSol from "./GovernorBravoInterfaces.sol";
export { Comp__factory } from "./Comp__factory";
export { GovernorBravoDelegate__factory } from "./GovernorBravoDelegate__factory";
export { GovernorBravoDelegator__factory } from "./GovernorBravoDelegator__factory";
