/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { CompLike } from "../CompLike";

export class CompLike__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CompLike {
    return new Contract(address, _abi, signerOrProvider) as CompLike;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "delegatee",
        type: "address",
      },
    ],
    name: "delegate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
