/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governorAlphaSol from "./GovernorAlpha.sol";
export type { governorAlphaSol };
import type * as governorBravoDelegateG1Sol from "./GovernorBravoDelegateG1.sol";
export type { governorBravoDelegateG1Sol };
import type * as governorBravoInterfacesSol from "./GovernorBravoInterfaces.sol";
export type { governorBravoInterfacesSol };
export type { Comp } from "./Comp";
export type { GovernorBravoDelegate } from "./GovernorBravoDelegate";
export type { GovernorBravoDelegator } from "./GovernorBravoDelegator";
