/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type {
  LinearCurve,
  LinearCurveInterface,
} from "../../amm.sol/LinearCurve";

const _abi = [
  {
    inputs: [],
    name: "PRECISION",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608e610038600b82828239805160001a607314602b57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063aaf5eb68146038575b600080fd5b6046670de0b6b3a764000081565b60405190815260200160405180910390f3fea2646970667358221220cc3bc51dd23757f1be1fa7e0af84495a4807379d55c753ee178230adc4a0efbd64736f6c634300080a0033";

type LinearCurveConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LinearCurveConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LinearCurve__factory extends ContractFactory {
  constructor(...args: LinearCurveConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<LinearCurve> {
    return super.deploy(overrides || {}) as Promise<LinearCurve>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): LinearCurve {
    return super.attach(address) as LinearCurve;
  }
  override connect(signer: Signer): LinearCurve__factory {
    return super.connect(signer) as LinearCurve__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LinearCurveInterface {
    return new utils.Interface(_abi) as LinearCurveInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LinearCurve {
    return new Contract(address, _abi, signerOrProvider) as LinearCurve;
  }
}
