/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155 } from "./ERC1155";
export type { ERC1155TokenReceiver } from "./ERC1155TokenReceiver";
export type { IERC3156FlashBorrower } from "./IERC3156FlashBorrower";
export type { IERC3156FlashLender } from "./IERC3156FlashLender";
