/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CompoundLens } from "./CompoundLens";
export type { ComptrollerLensInterface } from "./ComptrollerLensInterface";
export type { GovernorBravoInterface } from "./GovernorBravoInterface";
