/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CDaiDelegate } from "./CDaiDelegate";
export type { DaiJoinLike } from "./DaiJoinLike";
export type { GemLike } from "./GemLike";
export type { PotLike } from "./PotLike";
export type { VatLike } from "./VatLike";
