/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CDelegateInterface__factory } from "./CDelegateInterface__factory";
export { CDelegationStorage__factory } from "./CDelegationStorage__factory";
export { CDelegatorInterface__factory } from "./CDelegatorInterface__factory";
export { CErc20Interface__factory } from "./CErc20Interface__factory";
export { CErc20Storage__factory } from "./CErc20Storage__factory";
export { CTokenInterface__factory } from "./CTokenInterface__factory";
export { CTokenStorage__factory } from "./CTokenStorage__factory";
