/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITotalAssetOracle__factory } from "./ITotalAssetOracle__factory";
export { TVault__factory } from "./TVault__factory";
